# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "MeetUp2" do

pod 'ArcGIS-Runtime-SDK-iOS'
pod 'Firebase', '>= 1.1.12'

end

target "MeetUp2Tests" do

pod 'ArcGIS-Runtime-SDK-iOS'
pod 'Firebase', '>= 1.1.12'

end

